export interface GoogleDocumentNonDisclosureAgreementContractServiceInterface {}

export class GoogleDocumentNonDisclosureAgreementContractService
    implements GoogleDocumentNonDisclosureAgreementContractServiceInterface {}
